version: '3.4'

services:
  ### PostgreSQL ###########################################
  postgres:
    image: postgres:alpine
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build:
      context: '..'
      dockerfile: 'Dockerfile'
    depends_on: 
      - postgres
    ports:
      - "${WEB_PORT}:7777"
    